POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "moha@1",
    "password": "0598707785"
}

# token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vaGFAMSIsImlkIjoiNjlmYjRjNmQ3YzJiNjgzNTRkYjgxNWVhIiwiaWF0IjoxNzc4MDc2ODc5LCJleHAiOjE3NzgwODA0Nzl9.6CiMpEDHREcuwGHxtkdU2EWmPZe0NOLLQ7hEyQo7RzY